### ISSUE TITLE
Addin is not exporting textures

### ISSUE THREAD

**Issue by vnoves** [EverseDevelopment/revit-glTF-exporter#99]

**Comment by mattiNis** [comment]
Thank you for this amazing library! 

Texture support would be important for us. Right now, having only base colors limits the realism of the models, especially for customer-facing visualizations.

To help move this forward, I'm placing a **$800 bounty** on an accepted PR of adding texture export functionality to this exporter

As a reference and possible inspiration, this other exporter includes texture handling, i found this exporter with texture support:
 https://github.com/xuzhusheng/RevitGltfExporter/blob/4e24d00ef40a9933b25852f85a6680c518a74578/RenderingMaterial.cs

Are you @vnoves or anybody else interested to implement this?

Br, Matti / visiofy.com

**Comment by vnoves** [comment]
Hi @mattiNis , thanks for the interest in the implementation of textures.

We will accept your generous offer and should be able to implement it by June 6th. We have already analyzed the case and should be able to move forward quickly. I will let you know as soon as we merge to production.

**Comment by mattiNis** [comment]
Hi, that’s great to hear – really appreciate you taking it on!

Thanks also for the quick analysis and timeline. Can’t wait to see textures working in production!

**Comment by vnoves** [comment]
Hi @mattiNis do you have any updates? We did some more polish to the tool and the latest release is [here](https://github.com/EverseDevelopment/revit-glTF-exporter/releases/download/v4.4.2573/Leia-glTF.exporter.4.4.2573.msi), please give it a look and let us know what you think!

**Comment by mattiNis** [comment]
Hi @vnoves!

Thank you for the first version! And sorry for the late reply. 
I tested it with Revit 2025. Here are some issues I encountered when testing with the [rac_basic_sample_project.rvt](https://help.autodesk.com/view/RVT/2025/ENU/?guid=GUID-61EF2F22-3A1F-4317-B925-1E85F138BE88) model:

Issues:

- The exporter is using the wrong image. It should only use the main texture, not bump or relief patterns. (Check "Grass" and "Roofing - Metal Standing Seam" materials in the sample model.)
- UV mapping issues on some objects. (Check the grass and concrete pile in the sample project. The UV coordinates for the terrain are all zero.)
- Texture position and scale settings are not exported. (Check the "Roofing - Asphalt" material in the sample project.)
- The colors appear to be brighter than they should be, possibly due to an incorrect color space conversion?
For example, the red color used in the roof should be RGB(174, 0, 0), but in the exported model it shows up as RGB(215, 0, 0) (Check "Roofing - Metal Standing Seam" material in sample model).

One more topic to discuss: The glTF format does not support Revit's Image Fade value, which defines how much the texture influences the final appearance of the material. In many materials, this value is set to 100%, meaning the material should appear fully textured. I suggest exporter sets material color to (255, 255, 255) (white) when a texture is set, this would visually approximate the expected result. But of course, this is entirely up to you.


Here’s an example image showing how the exported model currently looks vs. how it should approximately look:
(Current on the left, expected on the right)

![Image](https://github.com/user-attachments/assets/40eee334-e827-4d8f-8020-f44fb900c47c)

Would you be able to fix these issues? It would be great if you could download the sample project and check the behavior with it after making the modifications.

Br, Matti

**Comment by vnoves** [comment]
Hi @mattiNis ,

Thanks so much for your feedback.
We will review with the team and make the necessary changes. The material's API in Revit, is limited, but I'm confident that we should be able to implement most of the comments.

Best,

**Comment by vnoves** [comment]
@mattiNis 

We've addressed all the comments, and the export now looks significantly improved. Please take another look and let us know your thoughts.

We’ve set the base color to white whenever a texture is present, and we’ve implemented a bitmap adjustment when a fade is applied—generating a new bitmap that incorporates the fade effect. I believe we could apply a similar approach for tint values as well, to ensure we’re covering all scenarios. What do you think?

![Image](https://github.com/user-attachments/assets/082152e2-8095-488b-932a-575395a59133)

Here is a [link ](https://github.com/EverseDevelopment/revit-glTF-exporter/releases/download/v4.4.3017/Leia-glTF.exporter.4.4.3017.msi)to the latest Installer

**Comment by mattiNis** [comment]
Hi @vnoves!

The texture export has improved a lot, thanks! 

The image fade looks great! I believe this is exactly the right approach. Applying the same logic for the tint effect sounds good to me as well. The exported colors now look correct.

I found only three issues with texture exports:

- Some textures are still missing. Please check the first screenshot I attached
- UV issues are mostly fixed, but there's still a problem with the sofa. See the second image for reference
- Textures seems to have an offset error. Look at the third image. It is not a problem in this case, but some users may have wooden paneling where the position of the seams is important

Let me know if I can help with further testing. Really appreciate the progress.

Br, Matti


![Image](https://github.com/user-attachments/assets/b1bdc969-0c31-4d3c-8109-7ea5183e6a8b)

![Image](https://github.com/user-attachments/assets/b08232b7-e8b1-4adb-a855-2ecfbd2ae1f7)

![Image](https://github.com/user-attachments/assets/bdb0cc0d-a146-421b-9900-47b8ddc7b871)

**Comment by vnoves** [comment]
Hi @mattiNis ,

Thanks so much for the feedback, and sorry about the back and forth. 

I have already adjusted the UVs in a way that is consistent on all objects, and now the mapping looks great. 
I have implemented the logic to incorporate the tint into the materials bitmap, and now, with the combination of texture + fade + tint, the colours look the same as Revit.
I fixed the offset in all materials, and now it matches the one in Revit.

Please find the latest Installer [Here](https://github.com/EverseDevelopment/revit-glTF-exporter/releases/download/v4.4.3698/Leia-glTF.exporter.4.4.3698.msi)

<img width="1664" height="822" alt="Image" src="https://github.com/user-attachments/assets/d5ea6193-678e-4acc-8f49-88fd76166a33" />

<img width="1809" height="831" alt="Image" src="https://github.com/user-attachments/assets/096c3f03-41b7-4cff-a68b-ce884c1bb91a" />

I have also tested,d and it works great with Revit Links

<img width="1652" height="789" alt="Image" src="https://github.com/user-attachments/assets/8839d36a-f2f1-4b3c-abab-7be0effc8e5c" />

**Comment by vnoves** [comment]
Hi @mattiNis did you have a chance to review the latest release? I'm also happy to jump on a call if that is more efficient for you. Thanks

**Comment by vnoves** [comment]
Hi @mattiNis let me know if there is anything that I can do to help you with the testing process. thanks
